version: "3.8"

volumes:
  postgres_volume:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
    expose:
      - 5432

  web:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env
    command: sh -c "alembic upgrade head && uvicorn main:app --reload --port 8000 --host 0.0.0.0"
